# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0004_remove_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('traveldatefrom', models.DateField()),
                ('traveldateto', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='allparticipants', to='login.User')),
                ('planned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsersDestinations', to='login.User')),
            ],
        ),
    ]
